### ISSUE TITLE
Investigate difference in pull distributions for 2D and 3D vonmisesfisher zenith/azimuth regressions.

### ISSUE THREAD

**Issue by RasmusOrsoe** [icecube/gnn-reco#51]
There seems to be differences in the distributions of pulls for zenith (perhaps azimuth too) between 2D and 3D vonmisesfisher.

Whats known:

- 3D vonmisesfisher needs factor 2 on sigma eg: `pull_3d = residual/2*np.sqrt(1/kappa)`
- 2D vonmisesfisher seems to not need factor 2
- May extend to azimuth

Question we need to answer:
 Is there difference in the general and the 'running quantile' pull plot for zenith and/or azimuth?  (see attachment and script for plotting code inspiration). 
[pull_investigation.zip](https://github.com/icecube/gnn-reco/files/7512679/pull_investigation.zip)

**Comment by asogaard** [comment]
Based on the studies in #73 it is seems that the pulls for the von Mises-Fisher in 3 dimensions, when applied to the reconstruction of a single angle, consistently have greater-than-unit variance (zenith and azimuth have been tested). What is more, the variance of the different pulls distributions seem to differ for the two angles (approx. 2.5 for zenith, approx. 3.0 for azimuth) meaning that a general, simple scaling (see https://github.com/icecube/gnn-reco/issues/51#issue-1049755041) does not seem feasible.

The answer to the last question, regd. "running quantile pull plots" is still open.
