### ISSUE TITLE
Decide on python version support

### ISSUE THREAD

**Issue by asogaard** [icecube/gnn-reco#9]
Should we support 2.7 and/or 3.x?

**Comment by asogaard** [comment]
I figure this comes down to standards/recommendations in IceCube, and what is commonly used on analysis/reconstruction. I figure @philippeller may be the one best equipped to answer this?

**Comment by RasmusOrsoe** [comment]
pytorch_geometric supports torch 1.9 and 1.8. When I look at https://pypi.org/project/torch/1.8.0/ I get the impression that torch doesn't support python older than 3. 

Also, the cvmfs that I have worked with (/cvmfs/icecube.opensciencegrid.org/users/Oscillation/software/oscNext_meta/releases/latest/build/env-shell.sh ) seems to not support python 3 - if this is true for all cvmfs I do not know. @philippeller  Probably knows!

**Comment by philippeller** [comment]
python 2.x is officially deprecated even in IceCube, but oscNext is still stuck in 2.x......i think focusing on the future, and given the fact that we can use newer icetray versions for reading/writing the oscNext files, i would be strongly against supporting any 2.x

**Comment by asogaard** [comment]
Completely agree, @philippeller. Perhaps a technical question, then: Right now we are working the IceTray shell environment provided by oscNext on CVMFS*, in order to use the `icecube` / `icecube.icetray` package(s) in the code. However, this oscNext environment, as you say, only supports python 2.x. Do you have a suggestion for how to best use these packages in python 3.x?

* /cvmfs/icecube.opensciencegrid.org/users/Oscillation/software/oscNext_meta/releases/latest/build/env-shell.sh

**Comment by philippeller** [comment]
We can simply use an official build? E.g. `py3-v4.1`, or whatever other version you fancy.
To use those from CVMFS, try these commands:
```shell
$ eval `/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/setup.sh`
$ /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/metaprojects/combo/stable/env-shell.sh
```
